---
name: Build Catalogs

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  lint-yaml:
    name: Build Catalogs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Golang
        uses: actions/setup-go@v5

      - name: Bundle schema.json
        run: cp schema.json catalog/schema.json

      - name: Create Catalog Manifest
        run: go run scripts/create_catalog.go

      - name: Create Catalog Manifest (Preview)
        run: go run scripts/_preview/create_catalog.go

      - name: Deploy To gh-pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          folder: catalog
