---
name: Update Catalog Entry

on:  # yamllint disable-line rule:truthy
  repository_dispatch:
    types: [update-entry]

jobs:
  update-catalog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      ENTRY: ${{ github.event.client_payload.entry }}
      VERSION: ${{ github.event.client_payload.version }}
      IMAGE: ${{ github.event.client_payload.image }}
      PREVIEW: ${{ github.event.client_payload.preview }}
      MANIFEST_PATH: >-
        ${{ github.event.client_payload.preview == '1'
            && format('catalog/_preview/{0}/manifest.yaml', github.event.client_payload.entry)
            || format('catalog/{0}/manifest.yaml', github.event.client_payload.entry) }}
    steps:
      - uses: actions/checkout@v4

      - name: Verify Parameters
        run: |
          echo "Version: ${VERSION}"
          echo "Preview: ${PREVIEW}"
          echo "Entry: ${ENTRY}"
          echo "Image: ${IMAGE}"
          echo "Manifest Path (generated): ${MANIFEST_PATH}"

          if [ -z "${VERSION}" ]; then
            echo "missing field 'version'"
            exit 1
          fi

          if [ -z "${ENTRY}" ]; then
            echo "missing field 'entry'"
            exit 1
          fi

          if [ -z "${IMAGE}" ]; then
            echo "missing field 'image'"
            exit 1
          fi

      - name: Set Entry Version And Image
        uses: mikefarah/yq@master
        env:
          # somehow env vars where missing in the yq action, so we reassign them
          ENTRY: ${{ github.event.client_payload.entry }}
          VERSION: ${{ github.event.client_payload.version }}
          PREVIEW: ${{ github.event.client_payload.preview }}
          IMAGE: ${{ github.event.client_payload.image }}
          MANIFEST_PATH: >-
            ${{ github.event.client_payload.preview == '1'
                && format('catalog/_preview/{0}/manifest.yaml', github.event.client_payload.entry)
                || format('catalog/{0}/manifest.yaml', github.event.client_payload.entry) }}
        with:
          cmd: |
            yq -i -I4 '.app.containerImage.image = strenv(IMAGE)' ${MANIFEST_PATH} && \
            yq -i -I4 '.version = strenv(VERSION)' ${MANIFEST_PATH}

      - name: Print Changes
        run: |
          cat ${MANIFEST_PATH}

      - name: Create PR
        env:
          GH_TOKEN: ${{ secrets.PAT_FOR_UPDATE_ACTION }}
        run: |
          BRANCH="feature/update-${ENTRY}-to-${VERSION}"

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git checkout -b $BRANCH

          git add ${MANIFEST_PATH}

          if [ "$PREVIEW" = "1" ]; then
            MSG="Update ${ENTRY} to ${VERSION} (Preview)"
          else
            MSG="Update ${ENTRY} to ${VERSION}"
          fi

          git commit -m "$MSG"
          git push -u origin $BRANCH

          gh pr create --title "$MSG" --body "Automated PR from ${ENTRY} release" --base main
          gh pr merge --squash --auto
